return {
    INITIALIZE = 'initialize',
    AUTHENTICATE = 'authenticate',
    SESSION_NEW = 'session/new',
    SESSION_LOAD = 'session/load',
    SESSION_SET_CONFIG_OPTION = 'session/set_config_option',
    SESSION_PROMPT = 'session/prompt',
    SESSION_CANCEL = 'session/cancel',
    SESSION_UPDATE = 'session/update',
    SESSION_REQUEST_PERMISSION = 'session/request_permission',
    FS_READ_TEXT_FILE = 'fs/read_text_file',
    FS_WRITE_TEXT_FILE = 'fs/write_text_file',
    TERMINAL_CREATE = 'terminal/create',
    TERMINAL_OUTPUT = 'terminal/output',
    TERMINAL_WAIT_FOR_EXIT = 'terminal/wait_for_exit',
    TERMINAL_KILL = 'terminal/kill',
    TERMINAL_RELEASE = 'terminal/release',
}
